FROM node:lts-alpine3.17
ENV NODE_ENV development
RUN apk update
RUN apk add git
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "yarn.lock", "./"]
RUN yarn
COPY . .
EXPOSE 3000
EXPOSE 24678
CMD ["yarn", "dev", "--host", "0.0.0.0"]